spring:
    datasource:
        url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
        driverClassName: org.h2.Driver
        username: sa
        password: 
    h2:
        console:
            path: /h2
            enabled: true
    jpa:
        database: h2
        hibernate:
            ddl-auto: create
        show-sql: true
